### ISSUE TITLE
Unable to use Scriptler script as source when the script result is not stable

### ISSUE THREAD

**Issue by RainerW** [Seitenbau/sb-jenkins-dynamicparameter#15]
com.seitenbau.jenkins.plugins.dynamicparameter.scriptler:ScriptlerChoiceParameterDefinition  :  checkParameterValue(StringParameterValue parameter) 

Does call getChoices() -> this invokes the script again! 

In case the script does not return a fixed value, e.g. a next project-version Number, or the current time, this will fail.

SHOULD

checkParameterValue() should verify the parameters against the parameters displayed to the users, and should not call the groovy code again.

**Comment by chbaranowski** [comment]
In the model we have at the moment not the displayed values. 
I think we need not check the actual value! 
Why should we check if the value is in the list?

**Comment by chbaranowski** [comment]
If anybody need the check please reopen the ticket.
