### ISSUE TITLE
Support for Jenkins CLI parameters submission

### ISSUE THREAD

**Issue by mbarczak** [Seitenbau/sb-jenkins-dynamicparameter#3]
Currently on Jenkins 1.471 / plugin 0.1.1 ,when trying to run build ( which is using Dynamic Choice Parameter )  from Jenkins CLI, build finishes with error : 

> "CLI parameter submission is not supported for the class com.seitenbau.jenkins.plugins.dynamicparameter.ChoiceParameterDefinition type. Please file a bug report for this"

It would be great to have such possibility.
Thanks.

**Comment by chbaranowski** [comment]
How to fix this issue? I override the method createValue(CLICommand command, String value) in the class BaseParameterDefinition. Now the method returns an instance of StringParameterValue.

Here the implementation:

``` java
    @Override
    public ParameterValue createValue(CLICommand command, String value) throws IOException, InterruptedException 
    {
        // Is this a fix for the issue https://github.com/Seitenbau/sb-jenkins-dynamicparameter/issues/3
        StringParameterValue parameterValue = new StringParameterValue(command.getName(), value);
        return checkParameterValue(parameterValue);
    }
```

Does this work?

**Comment by mbarczak** [comment]
Thanks for rapid reaction . After your change, build no longer fails after calling it through CLI , but instead of creating proper parameter name ("BUILD_TARGET" in my case) , it creates parameter "build" . If you change : 

``` java
StringParameterValue parameterValue = new StringParameterValue(command.getName(), value);
```

to 

``` java
StringParameterValue parameterValue = new StringParameterValue(this.getName(), value);
```

it works perfectly. That's because <i>commnad.getName()</i> returns name of the command used through CLI ("build" in my case) , and <i>this.getName()</i> returns actual parameter name. 
Thank you for your time and looking forward for release with fix.

**Comment by chbaranowski** [comment]
ok changed the implementation to

``` java
StringParameterValue parameterValue = new StringParameterValue(this.getName(), value);
```
