### ISSUE TITLE
Disabled UI elements for parameters

### ISSUE THREAD

**Issue by sodabrew** [Seitenbau/sb-jenkins-dynamicparameter#4]
Hi, I'd like to be able to set certain parameters as disabled in the UI -- that is, when you go to trigger the build, you can see what the Groovy script has inserted into a field, but the form elements are disabled.

(Yes, this could be worked around with a simple Greasemonkey script, but the convenience of not accidentally changing a parameter is good enough for my purposes.)

**Comment by omehegan** [comment]
I would like this feature too.

**Comment by chbaranowski** [comment]
Add support for readonly parameters in the master. At the moment the readonly flag only works for the parameter type StringParameter (Dynamic Parameter). Will add also support for the other parameter types. Is readonly ok or do you really need disabled parameters?

**Comment by omehegan** [comment]
Not sure what the difference between readonly and disabled would be. We just want it so that when you run a build and see the output of your dynamic script in the text box, you can't then EDIT the output before actually starting the build.

**Comment by chbaranowski** [comment]
ok thats how I will implemented it. We plan next week a release which will contain this feature.
