### ISSUE TITLE
Dynamic parameter script does not fire for builds triggered by API

### ISSUE THREAD

**Issue by omehegan** [Seitenbau/sb-jenkins-dynamicparameter#5]
If you create a dynamic parameter for a job, and use a Groovy script for the default value, that value is not set when you trigger the job via the HTTP API. I.e. if I run 'curl http://jenkins/jobs/my_job/buildWithParameters?cause=Git+checkin' the parameter value will not be populated.

**Comment by chbaranowski** [comment]
close #5 - not fixed
The same issue is for non dynamic parameters. I think the option buildWithParameters ignores all parameters. Will close the ticket did not find a solution for the issues.
