### ISSUE TITLE
setupLocalClassPaths should expand to *.jar files

### ISSUE THREAD

**Issue by ghost** [Seitenbau/sb-jenkins-dynamicparameter#9]
great plugin, thank you!

but, the following invocation:

```
ScriptParameterDefinition.setupLocalClassPaths(....
```

which is ultimately used by 

```
JenkinsUtils.execute(...
      config.setClasspathList(classPathList);
      GroovyShell groovyShell = new GroovyShell(config);
      Object evaluate = groovyShell.evaluate(script);
```

currently supplies list of directories, such as

```
/var/lib/jenkins/dynamic_parameter/classpath/library-one/
/var/lib/jenkins/dynamic_parameter/classpath/library-two/
```

GroovyShell can not use these folders; they need to be expanded to actual jars, such as:

```
/var/lib/jenkins/dynamic_parameter/classpath/library-one/file-10.jar
/var/lib/jenkins/dynamic_parameter/classpath/library-one/file-11.jar
/var/lib/jenkins/dynamic_parameter/classpath/library-two/file-20.jar
/var/lib/jenkins/dynamic_parameter/classpath/library-two/file-21.jar
```

**Comment by ghost** [comment]
Hi everyone. I need this bug/feature so much that I'm willing to pay 5.00 bucks for it.
This offer is registered at FreedomSponsors (http://www.freedomsponsors.org/core/issue/73/setuplocalclasspaths-should-expand-to-jar-files).
Once you solve it (according to the acceptance criteria described there), just create a FreedomSponsors account and mark it as resolved (oh, you'll need a Paypal account too)
I'll then check it out and will gladly pay up!

If anyone else would like to throw in a few bucks to elevate the priority on this issue, you should check out FreedomSponsors!

**Comment by ghost** [comment]
alternatively, you could use wildcard "path/*"

**Comment by chbaranowski** [comment]
fixed in the master branch should be part of next release.
